export interface ThemeColors {
    bg: string;
    border: string;
    text: string;
    accentBorder: string;
    accentText: string;
    tabActive: string;
    tabInactive: string;
    meritButton: string;
    flawButton: string;
    footerText: string;
    headerButton: string;
    emptyText: string;
    descriptionText: string;
    meritBadge: string;
    flawBadge: string;
    removeButton: string;
    disabledButton: string;
    counterButton: string;
    checkedBg: string;   // ← für HealthBox-Kästchen
}

export type ThemeName = 'emerald' | 'amber' | 'purple' | 'sky' | 'vampire' | 'werewolf' | 'mage' | 'changeling' | 'wraith';

export const themeConfig: Record<ThemeName, ThemeColors> = {
    emerald: {
        bg:              'bg-emerald-950/90',
        border:          'border-emerald-800',
        text:            'text-emerald-100',
        accentBorder:    'border-emerald-500',
        accentText:      'text-emerald-300',
        tabActive:       'border-emerald-500 text-emerald-300',
        tabInactive:     'text-emerald-500 hover:text-emerald-300',
        meritButton:     'bg-emerald-800 hover:bg-emerald-700 text-white',
        flawButton:      'bg-rose-800 hover:bg-rose-700 text-white',
        footerText:      'text-emerald-400',
        headerButton:    'text-emerald-400 hover:text-emerald-200',
        emptyText:       'text-emerald-500',
        descriptionText: 'text-emerald-400',
        meritBadge:      'bg-emerald-800 text-emerald-200',
        flawBadge:       'bg-rose-800 text-rose-200',
        removeButton:    'bg-gray-700 hover:bg-gray-600 text-white',
        disabledButton:  'bg-gray-700 opacity-50 cursor-not-allowed',
        counterButton:   'bg-emerald-800 hover:bg-emerald-700 text-white',
        checkedBg:       'bg-emerald-700',
    },
    amber: {
        bg:              'bg-amber-950/90',
        border:          'border-amber-800',
        text:            'text-amber-100',
        accentBorder:    'border-amber-500',
        accentText:      'text-amber-300',
        tabActive:       'border-amber-500 text-amber-300',
        tabInactive:     'text-amber-500 hover:text-amber-300',
        meritButton:     'bg-amber-800 hover:bg-amber-700 text-white',
        flawButton:      'bg-rose-800 hover:bg-rose-700 text-white',
        footerText:      'text-amber-400',
        headerButton:    'text-amber-400 hover:text-amber-200',
        emptyText:       'text-amber-500',
        descriptionText: 'text-amber-400',
        meritBadge:      'bg-amber-800 text-amber-200',
        flawBadge:       'bg-rose-800 text-rose-200',
        removeButton:    'bg-gray-700 hover:bg-gray-600 text-white',
        disabledButton:  'bg-gray-700 opacity-50 cursor-not-allowed',
        counterButton:   'bg-amber-800 hover:bg-amber-700 text-white',
        checkedBg:       'bg-amber-700',
    },
    purple: {
        bg:              'bg-purple-950/90',
        border:          'border-purple-800',
        text:            'text-purple-100',
        accentBorder:    'border-purple-500',
        accentText:      'text-purple-300',
        tabActive:       'border-purple-500 text-purple-300',
        tabInactive:     'text-purple-500 hover:text-purple-300',
        meritButton:     'bg-purple-800 hover:bg-purple-700 text-white',
        flawButton:      'bg-rose-800 hover:bg-rose-700 text-white',
        footerText:      'text-purple-400',
        headerButton:    'text-purple-400 hover:text-purple-200',
        emptyText:       'text-purple-500',
        descriptionText: 'text-purple-400',
        meritBadge:      'bg-purple-800 text-purple-200',
        flawBadge:       'bg-rose-800 text-rose-200',
        removeButton:    'bg-gray-700 hover:bg-gray-600 text-white',
        disabledButton:  'bg-gray-700 opacity-50 cursor-not-allowed',
        counterButton:   'bg-purple-800 hover:bg-purple-700 text-white',
        checkedBg:       'bg-purple-700',
    },
    sky: {
        bg:              'bg-sky-950/90',
        border:          'border-sky-800',
        text:            'text-sky-100',
        accentBorder:    'border-sky-500',
        accentText:      'text-sky-300',
        tabActive:       'border-sky-500 text-sky-300',
        tabInactive:     'text-sky-500 hover:text-sky-300',
        meritButton:     'bg-sky-800 hover:bg-sky-700 text-white',
        flawButton:      'bg-rose-800 hover:bg-rose-700 text-white',
        footerText:      'text-sky-400',
        headerButton:    'text-sky-400 hover:text-sky-200',
        emptyText:       'text-sky-500',
        descriptionText: 'text-sky-400',
        meritBadge:      'bg-sky-800 text-sky-200',
        flawBadge:       'bg-rose-800 text-rose-200',
        removeButton:    'bg-gray-700 hover:bg-gray-600 text-white',
        disabledButton:  'bg-gray-700 opacity-50 cursor-not-allowed',
        counterButton:   'bg-sky-800 hover:bg-sky-700 text-white',
        checkedBg:       'bg-sky-700',
    },
    vampire: {
        bg:              'bg-red-950/90',
        border:          'border-red-800',
        text:            'text-red-100',
        accentBorder:    'border-red-500',
        accentText:      'text-red-300',
        tabActive:       'border-red-500 text-red-300',
        tabInactive:     'text-red-500 hover:text-red-300',
        meritButton:     'bg-red-800 hover:bg-red-700 text-white',
        flawButton:      'bg-rose-800 hover:bg-rose-700 text-white',
        footerText:      'text-red-400',
        headerButton:    'text-red-400 hover:text-red-200',
        emptyText:       'text-red-500',
        descriptionText: 'text-red-400',
        meritBadge:      'bg-red-800 text-red-200',
        flawBadge:       'bg-rose-800 text-rose-200',
        removeButton:    'bg-gray-700 hover:bg-gray-600 text-white',
        disabledButton:  'bg-gray-700 opacity-50 cursor-not-allowed',
        counterButton:   'bg-red-800 hover:bg-red-700 text-white',
        checkedBg:       'bg-red-700',
    },
    werewolf: {
        bg:              'bg-gray-950/90',
        border:          'border-gray-800',
        text:            'text-gray-100',
        accentBorder:    'border-emerald-500',
        accentText:      'text-emerald-300',
        tabActive:       'border-emerald-500 text-emerald-300',
        tabInactive:     'text-emerald-500 hover:text-emerald-300',
        meritButton:     'bg-gray-800 hover:bg-gray-700 text-white',
        flawButton:      'bg-rose-800 hover:bg-rose-700 text-white',
        footerText:      'text-emerald-400',
        headerButton:    'text-emerald-400 hover:text-emerald-200',
        emptyText:       'text-emerald-500',
        descriptionText: 'text-emerald-400',
        meritBadge:      'bg-gray-800 text-gray-200',
        flawBadge:       'bg-rose-800 text-rose-200',
        removeButton:    'bg-gray-700 hover:bg-gray-600 text-white',
        disabledButton:  'bg-gray-700 opacity-50 cursor-not-allowed',
        counterButton:   'bg-gray-800 hover:bg-gray-700 text-white',
        checkedBg:       'bg-emerald-700',
    },
    mage: {
        bg:              'bg-indigo-950/90',
        border:          'border-indigo-800',
        text:            'text-indigo-100',
        accentBorder:    'border-indigo-500',
        accentText:      'text-indigo-300',
        tabActive:       'border-indigo-500 text-indigo-300',
        tabInactive:     'text-indigo-500 hover:text-indigo-300',
        meritButton:     'bg-indigo-800 hover:bg-indigo-700 text-white',
        flawButton:      'bg-rose-800 hover:bg-rose-700 text-white',
        footerText:      'text-indigo-400',
        headerButton:    'text-indigo-400 hover:text-indigo-200',
        emptyText:       'text-indigo-500',
        descriptionText: 'text-indigo-400',
        meritBadge:      'bg-indigo-800 text-indigo-200',
        flawBadge:       'bg-rose-800 text-rose-200',
        removeButton:    'bg-gray-700 hover:bg-gray-600 text-white',
        disabledButton:  'bg-gray-700 opacity-50 cursor-not-allowed',
        counterButton:   'bg-indigo-800 hover:bg-indigo-700 text-white',
        checkedBg:       'bg-indigo-700',
    },
    changeling: {
        bg:              'bg-green-950/90',
        border:          'border-green-800',
        text:            'text-green-100',
        accentBorder:    'border-yellow-600',
        accentText:      'text-yellow-300',
        tabActive:       'border-yellow-600 text-yellow-300',
        tabInactive:     'text-yellow-600 hover:text-yellow-300',
        meritButton:     'bg-green-800 hover:bg-green-700 text-white',
        flawButton:      'bg-rose-800 hover:bg-rose-700 text-white',
        footerText:      'text-yellow-400',
        headerButton:    'text-yellow-400 hover:text-yellow-200',
        emptyText:       'text-yellow-500',
        descriptionText: 'text-yellow-400',
        meritBadge:      'bg-green-800 text-green-200',
        flawBadge:       'bg-rose-800 text-rose-200',
        removeButton:    'bg-gray-700 hover:bg-gray-600 text-white',
        disabledButton:  'bg-gray-700 opacity-50 cursor-not-allowed',
        counterButton:   'bg-green-800 hover:bg-green-700 text-white',
        checkedBg:       'bg-yellow-700',
    },
    wraith: {
        bg:              'bg-slate-950/90',
        border:          'border-slate-800',
        text:            'text-slate-100',
        accentBorder:    'border-cyan-500',
        accentText:      'text-cyan-300',
        tabActive:       'border-cyan-500 text-cyan-300',
        tabInactive:     'text-cyan-500 hover:text-cyan-300',
        meritButton:     'bg-slate-800 hover:bg-slate-700 text-white',
        flawButton:      'bg-rose-800 hover:bg-rose-700 text-white',
        footerText:      'text-cyan-400',
        headerButton:    'text-cyan-400 hover:text-cyan-200',
        emptyText:       'text-cyan-500',
        descriptionText: 'text-cyan-400',
        meritBadge:      'bg-slate-800 text-slate-200',
        flawBadge:       'bg-rose-800 text-rose-200',
        removeButton:    'bg-gray-700 hover:bg-gray-600 text-white',
        disabledButton:  'bg-gray-700 opacity-50 cursor-not-allowed',
        counterButton:   'bg-slate-800 hover:bg-slate-700 text-white',
        checkedBg:       'bg-cyan-700',
    },
};